# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        
        # Create layout
        self.main_layout = QtWidgets.QVBoxLayout(Form)
        
        # Create header layout for icons
        self.header_layout = QtWidgets.QHBoxLayout()
        
        # Add Pico status icon (left)
        self.pico_status = QtWidgets.QLabel(parent=Form)
        self.pico_status.setFixedSize(50, 70)  # Increased height, adjusted width
        self.pico_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pico_status.setObjectName("pico_status")
        self.header_layout.addWidget(self.pico_status)
        
        # Add title label
        self.title_label = QtWidgets.QLabel("Atlas ROV", parent=Form)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.header_layout.addWidget(self.title_label)
        
        # Add controller status icon (right)
        self.controller_status = QtWidgets.QLabel(parent=Form)
        self.controller_status.setFixedSize(70, 70)  # Made square but larger
        self.controller_status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.controller_status.setObjectName("controller_status")
        self.header_layout.addWidget(self.controller_status)
        
        # Add header layout to main layout
        self.main_layout.addLayout(self.header_layout)
        
        # Add vertical spacing after header
        spacer = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, 
                                     QtWidgets.QSizePolicy.Policy.Fixed)
        self.main_layout.addItem(spacer)
        
        self.grid_layout = QtWidgets.QGridLayout()
        self.button_layout = QtWidgets.QHBoxLayout()
        
        # Add spacing and margins
        self.main_layout.setContentsMargins(20, 20, 20, 20)
        self.main_layout.setSpacing(15)
        self.grid_layout.setSpacing(10)
        
        # Initialize widgets
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        
        # Initialize widgets with fixed height
        label_height = 40  # Adjust this value as needed
        
        # Setup labels with consistent sizes
        for i, (label_name, value_name) in enumerate([
            (self.label, self.label_7),
            (self.label_2, self.label_8),
            (self.label_3, self.label_9),
            (self.label_4, self.label_10),
            (self.label_5, self.label_11),
            (self.label_6, self.label_12)
        ]):
            label_name.setMinimumHeight(label_height)
            value_name.setMinimumHeight(label_height)
            self.grid_layout.addWidget(label_name, i, 0)
            self.grid_layout.addWidget(value_name, i, 1)
        
        # Setup buttons
        self.button_layout.addWidget(self.pushButton)
        self.button_layout.addWidget(self.pushButton_2)
        
        self.button_layout.setSpacing(20)
        
        # Add layouts to main layout
        self.main_layout.addLayout(self.grid_layout)
        self.main_layout.addStretch()
        self.main_layout.addLayout(self.button_layout)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "Motion"))
        self.label_2.setText(_translate("Form", "Gripper 1"))
        self.label_3.setText(_translate("Form", "Gripper 2"))
        self.pushButton_2.setText(_translate("Form", "Stop/Reset"))
        self.label_4.setText(_translate("Form", "Gripper 3"))
        self.label_5.setText(_translate("Form", "Gripper 4"))
        self.label_6.setText(_translate("Form", "Speed"))
        self.label_7.setText(_translate("Form", "None"))
        self.label_8.setText(_translate("Form", "None"))
        self.label_9.setText(_translate("Form", "None"))
        self.label_10.setText(_translate("Form", "None"))
        self.label_11.setText(_translate("Form", "None"))
        self.label_12.setText(_translate("Form", "None"))
